package miu;

/*
 * Write a function which computes the Guthrie index of its argument
The Guthrie sequence of a positive number n is defined to be the numbers generated by the algorithm below.
	-	Start with a positive number n
	-	if n is even then divide by 2
	-	if n is odd then multiply by 3 and add 1
For example, the Guthrie sequence of the number 7 is 7,  22, 11, 34, 17, 52, 26, 13, 40, 20, 10, 5, 16, 8, 4, 2, 1
*/

public class GuthrieIndex {
	public static void main(String[] args) {
		int a = 7;
		int result = guthrieIndex(a);
		System.out.println(result);
	}

	static int guthrieIndex(int a) {
		int guthrieIndex = 0;
		while (a > 1) {
			if (a % 2 == 0)
				a = a / 2;
			else
				a = ((a * 3) + 1);
			guthrieIndex++;
		}

		return guthrieIndex;

	}
}
